#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove solid properties
rm constant/solidProperties

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
\rm -f constant/polyMesh/boundary case.foam
\rm -rf system/*Subset constant/*Subset postProcessing
\rm residual.dat BCloopCorr.dat  
\rm *.foam

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
