#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Copy og directory
rm -r 0
cp -r 0_org 0

cleanCase
\rm -f constant/polyMesh/boundary case.foam
\rm -rf system/*Subset constant/*Subset postProcessing
\rm residual.dat BCloopCorr.dat
\rm *.foam

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
