#!/bin/bash

rm solidProperties

cd ML_model

read -r -p "Are you sure you want to remove machine learning model [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        ./Allclean

        ./cleanSolidProperties
        ;;
    *)
        ;;
esac
