#!/bin/bash

cd mesh10/plateHole 

./Allclean

cd ../../mesh100/plateHole

./Allclean

cd ../plateHole_ML 

./Allclean

cd ../../machine_learning


read -r -p "Are you sure you want to remove machine learning model [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        ./Allclean
        ;;
    *)
        ;;
esac
